import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Search from "../components/search.jsx"
import Rocket from "../images/rocket.gif"
import Flex from "../components/flex.jsx"
import { useEffect, useState } from 'react'

export default function Home() {
  const code = () =>{
    if(process.browser)
    {
      const [Rocket, setRocket] = useState(document.querySelector(".Rocket"))
      useEffect(() => {
        setTimeout(() => {
        Rocket.remove()
        }, 10000);
      }, []) 
  }
    }
    code()

  return (
    <div className={styles.body}>

      <Head>
        <title>X-Localyza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Search />
      <Image src={Rocket} className="Rocket"  />
  <Flex />
    </div>
  )
}