import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Rocket from "../images/rocket.gif"

export default function Home() {
  return (
    <div className={styles.body}>
      <Head>
        <title>X-Localyza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
   <Image src={Rocket} className="Rocket" />

     </div>
  )
}