import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Rocket from "../images/rocket.gif"
import Flex from "../components/flex.jsx"

export default function Home() {
  const code = () =>{
    if(process.browser)
    {
      const rocket = document.querySelectorAll(".Rocket")
     setTimeout(() => {
      rocket[0].remove()
     }, 10000);
  }
    }
    code()

  return (
    <div className={styles.body}>

      <Head>
        <title>X-Localyza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Image src={Rocket} className="Rocket"  />
  <Flex />
    </div>
  )
}